-- CONES GitHub Issues / Projects relational schema for Supabase PostgreSQL.
-- This schema does not modify the CONES application's commerce tables.

create table if not exists public.projects (
  project_id bigint generated by default as identity primary key,
  project_name text not null,
  github_repo_full_name text not null unique,
  github_project_number integer,
  github_project_url text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  user_id bigint generated by default as identity primary key,
  github_username text not null unique,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.statuses (
  status_id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(project_id) on delete cascade,
  status_name text not null,
  position integer not null check (position >= 0),
  is_done boolean not null default false,
  unique (project_id, status_name),
  unique (project_id, position),
  unique (project_id, status_id)
);

create table if not exists public.milestones (
  milestone_id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(project_id) on delete cascade,
  github_milestone_number integer,
  title text not null,
  state text not null check (state in ('open', 'closed')),
  due_date date,
  unique (project_id, github_milestone_number),
  unique (project_id, milestone_id)
);

create table if not exists public.tasks (
  task_id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(project_id) on delete cascade,
  status_id bigint,
  milestone_id bigint,
  author_id bigint references public.users(user_id) on delete set null,
  github_issue_number integer not null,
  github_project_item_id text,
  issue_url text not null unique,
  title text not null,
  body text,
  issue_state text not null check (issue_state in ('open', 'closed')),
  created_at timestamptz not null,
  closed_at timestamptz,
  status_position integer check (status_position >= 0),
  card_position integer check (card_position >= 1),
  unique (project_id, github_issue_number),
  foreign key (project_id, status_id)
    references public.statuses(project_id, status_id) on delete restrict,
  foreign key (project_id, milestone_id)
    references public.milestones(project_id, milestone_id) on delete set null,
  check (closed_at is null or closed_at >= created_at)
);

create table if not exists public.task_assignees (
  task_id bigint not null references public.tasks(task_id) on delete cascade,
  user_id bigint not null references public.users(user_id) on delete cascade,
  assigned_at timestamptz not null default now(),
  primary key (task_id, user_id)
);

create index if not exists statuses_project_position_idx
  on public.statuses (project_id, position);
create index if not exists tasks_project_status_idx
  on public.tasks (project_id, status_id);
create index if not exists tasks_milestone_idx
  on public.tasks (milestone_id);
create index if not exists task_assignees_user_idx
  on public.task_assignees (user_id);

comment on column public.tasks.status_id is
  'Kanban status observed from the 2026-09-25 public View 1 snapshot; nullable for future imports without a verified board status.';
comment on column public.tasks.github_project_item_id is
  'GitHub Projects V2 item node ID, populated only from a verified Project export/API response.';
