-- Minimal CONES View 1 seed from data/raw/cones-project-view1.tsv.
-- Issue state and optional Milestone are read from data/raw/cones-issues.json.
-- Full source payload is preserved in data/raw; it is not copied into tasks.
begin;
insert into public.projects (project_name,github_repo_full_name,github_project_number,github_project_url) values ('CONES','seune-h0203/cones',3,'https://github.com/users/seune-h0203/projects/3') on conflict (github_repo_full_name) do update set project_name=excluded.project_name,github_project_number=excluded.github_project_number,github_project_url=excluded.github_project_url;
insert into public.users (github_username,display_name) values ('Hamchaelim','Hamchaelim'),('ohoobae','ohoobae'),('qkrtpfls03','qkrtpfls03'),('seune-h0203','seune-h0203') on conflict (github_username) do update set display_name=excluded.display_name;
insert into public.statuses (project_id,status_name,position,is_done) select project_id,v.status_name,v.position,v.is_done from public.projects cross join (values ('Todo',0,false),('In Progress',1,false),('Done',2,true)) v(status_name,position,is_done) where github_repo_full_name='seune-h0203/cones' on conflict (project_id,status_name) do update set position=excluded.position,is_done=excluded.is_done;
insert into public.milestones (project_id,github_milestone_number,title,state) select project_id,1,'CONES — FINAL SUBMISSION','open' from public.projects where github_repo_full_name='seune-h0203/cones' on conflict (project_id,github_milestone_number) do update set title=excluded.title,state=excluded.state;
delete from public.task_assignees ta using public.tasks t join public.projects p on p.project_id=t.project_id where ta.task_id=t.task_id and p.github_repo_full_name='seune-h0203/cones';
delete from public.tasks t using public.projects p where p.project_id=t.project_id and p.github_repo_full_name='seune-h0203/cones';
insert into public.tasks (project_id,status_id,milestone_id,github_issue_number,issue_url,title,issue_state)
select p.project_id,s.status_id,m.milestone_id,v.issue_number,v.issue_url,v.title,v.issue_state from public.projects p cross join (values
(9, 'In Progress', 'https://github.com/seune-h0203/cones/issues/9', '[QA] Animation 및 Interaction 최종 테스트', 'open', 'CONES — FINAL SUBMISSION'),
(13, 'In Progress', 'https://github.com/seune-h0203/cones/issues/13', '[PRESENTATION] 3분 발표 및 Demo 준비', 'open', 'CONES — FINAL SUBMISSION'),
(39, 'In Progress', 'https://github.com/seune-h0203/cones/issues/39', '[PRESENTATION] 발표 대본 준비', 'open', null),
(3, 'Done', 'https://github.com/seune-h0203/cones/issues/3', '[FE] 전체 페이지 콘텐츠 연결 검수', 'closed', 'CONES — FINAL SUBMISSION'),
(1, 'Done', 'https://github.com/seune-h0203/cones/issues/1', '[PLAN] CONES 프로젝트 최종 작업 관리', 'closed', 'CONES — FINAL SUBMISSION'),
(2, 'Done', 'https://github.com/seune-h0203/cones/issues/2', '[CONTENT] 아티스트 정보 최종 검수', 'closed', 'CONES — FINAL SUBMISSION'),
(4, 'Done', 'https://github.com/seune-h0203/cones/issues/4', '[FE] 이미지 및 Asset 경로 최종 검수', 'closed', 'CONES — FINAL SUBMISSION'),
(5, 'Done', 'https://github.com/seune-h0203/cones/issues/5', '[FE] Teaser Video Manifest 최종 검수', 'closed', 'CONES — FINAL SUBMISSION'),
(6, 'Done', 'https://github.com/seune-h0203/cones/issues/6', '[FE] GitHub Pages Routing 최종 검수', 'closed', 'CONES — FINAL SUBMISSION'),
(7, 'Done', 'https://github.com/seune-h0203/cones/issues/7', '[QA] Desktop 반응형 테스트', 'closed', 'CONES — FINAL SUBMISSION'),
(10, 'Done', 'https://github.com/seune-h0203/cones/issues/10', '[QA] Accessibility 최종 검수', 'closed', 'CONES — FINAL SUBMISSION'),
(11, 'Done', 'https://github.com/seune-h0203/cones/issues/11', '[QA] Production Build 테스트', 'closed', 'CONES — FINAL SUBMISSION'),
(12, 'Done', 'https://github.com/seune-h0203/cones/issues/12', '[DEPLOY] GitHub Pages 최종 배포 확인', 'closed', 'CONES — FINAL SUBMISSION'),
(32, 'Done', 'https://github.com/seune-h0203/cones/issues/32', '[BE] Supabase 커머스 백엔드(스키마·RLS·RPC) 구축', 'closed', null),
(33, 'Done', 'https://github.com/seune-h0203/cones/issues/33', '[FE] Shop/Cart/Checkout/Order 커머스 프론트엔드 구현', 'closed', null),
(34, 'Done', 'https://github.com/seune-h0203/cones/issues/34', '[DB] order_items 이미지 컬럼 추가 및 주문 데이터 마이그레이션', 'closed', null),
(35, 'Done', 'https://github.com/seune-h0203/cones/issues/35', '[FIX] 라우팅 서브패스 및 이미지 경로 버그 수정', 'closed', null),
(36, 'Done', 'https://github.com/seune-h0203/cones/issues/36', '[DEVOPS] GitHub Actions 배포 워크플로 Supabase 환경변수 연동', 'closed', null),
(37, 'Done', 'https://github.com/seune-h0203/cones/issues/37', '[DOCS] README 구조 개편 및 멤버 데이터 정합성 수정', 'closed', null)) v(issue_number,status_name,issue_url,title,issue_state,milestone_title) join public.statuses s on s.project_id=p.project_id and s.status_name=v.status_name left join public.milestones m on m.project_id=p.project_id and m.title=v.milestone_title where p.github_repo_full_name='seune-h0203/cones';
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='Hamchaelim' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=9 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='seune-h0203' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=13 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='ohoobae' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=39 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='seune-h0203' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=3 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='qkrtpfls03' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=3 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='seune-h0203' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=1 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='qkrtpfls03' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=1 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='ohoobae' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=2 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='qkrtpfls03' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=2 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='Hamchaelim' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=4 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='ohoobae' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=4 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='ohoobae' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=5 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='seune-h0203' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=6 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='qkrtpfls03' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=6 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='Hamchaelim' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=7 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='Hamchaelim' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=10 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='Hamchaelim' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=11 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='Hamchaelim' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=12 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='ohoobae' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=32 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='seune-h0203' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=32 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='seune-h0203' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=33 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='qkrtpfls03' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=33 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='seune-h0203' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=34 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='seune-h0203' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=35 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='seune-h0203' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=36 on conflict do nothing;
insert into public.task_assignees(task_id,user_id) select t.task_id,u.user_id from public.tasks t join public.projects p on p.project_id=t.project_id join public.users u on u.github_username='seune-h0203' where p.github_repo_full_name='seune-h0203/cones' and t.github_issue_number=37 on conflict do nothing;
commit;