-- Verified enrichment for the 19 CONES View 1 cards.
-- Issue body comes from cones-issues.json; comments come from GitHub Issue comments API.
-- Timeline/project status history tables are prepared separately because status before/after values are not present in the verified payload.
begin;
create table if not exists public.issue_details (task_id bigint primary key references public.tasks(task_id) on delete cascade, github_issue_id bigint not null unique, author_login text, body text not null default '', created_at timestamptz not null, updated_at timestamptz not null, closed_at timestamptz, source_url text not null unique);
create table if not exists public.issue_comments (comment_id bigint primary key, task_id bigint not null references public.tasks(task_id) on delete cascade, author_login text not null, created_at timestamptz not null, updated_at timestamptz not null, body text not null, source_url text not null unique);
create table if not exists public.issue_timeline_events (event_id bigint primary key, task_id bigint references public.tasks(task_id) on delete cascade, event_type text not null, actor_login text, occurred_at timestamptz not null, source_url text not null unique, metadata jsonb not null default '{}'::jsonb, verification_status text not null default 'unconfirmed' check (verification_status in ('verified','unconfirmed')), note text);
create table if not exists public.project_status_history (status_history_id bigint generated by default as identity primary key, task_id bigint references public.tasks(task_id) on delete cascade, source_event_id bigint unique references public.issue_timeline_events(event_id) on delete cascade, occurred_at timestamptz not null, actor_login text, from_status_id bigint, to_status_id bigint, verification_status text not null check (verification_status in ('verified','unconfirmed')), note text not null);
create index if not exists issue_comments_task_created_idx on public.issue_comments(task_id, created_at);
create index if not exists issue_events_task_occurred_idx on public.issue_timeline_events(task_id, occurred_at);
create index if not exists project_status_history_task_occurred_idx on public.project_status_history(task_id, occurred_at);
alter table public.issue_details disable row level security;
alter table public.issue_comments disable row level security;
insert into public.issue_details(task_id,github_issue_id,author_login,body,created_at,updated_at,closed_at,source_url) select t.task_id,v.github_issue_id,v.author_login,v.body,v.created_at::timestamptz,v.updated_at::timestamptz,nullif(v.closed_at,'')::timestamptz,v.source_url from public.tasks t join (values
(39,5445442999,'ohoobae','','2026-09-14T05:10:00Z','2026-09-14T05:10:16Z','','https://github.com/seune-h0203/cones/issues/39'),
(37,5434529674,'seune-h0203','## 작업 목적

README의 목차가 10장으로 늘어나며 가독성이 떨어지고, 팀명 어원 설명이 여러 장에서 반복되며, 멤버 능력 순환 명칭(THINK/BUILD vs LEARN/DESIGN)이 장마다 다르게 쓰이고, 멤버 데이터(팬덤·생일)가 일부만 채워져 있던 문제를 정리한다.

## 구현 내용

- 목차를 10장 → 7장으로 축소 (개요 / 멤버 / 세계관 / 프로젝트 / 기술 / 협업과 기록 / 여담), 옛 UNIT 심화 챕터·GitHub/Daily Snapshot/활동/기록 챕터를 상위 챕터로 통합
- 그룹명 어원(CON + ONES) 설명을 1장에만 두고 다른 장에서는 참조만 하도록 정리
- 능력 순환 명칭을 코드와 일치하는 `LEARN → PREDICT → DESIGN → EXECUTE`로 전 문서 통일, 서사용으로만 쓰이던 THINK/BUILD 명칭 제거
- 신규 커머스 기능을 설명하는 "4.4. OFFICIAL MD" 장 추가
- Tech Stack / 프로젝트 구조 / 배포 설명을 실제 최신 코드(라우팅, Supabase, contexts/lib 폴더 등) 기준으로 갱신 — "react-router-dom 미사용" 등 더 이상 사실이 아닌 서술 수정
- `src/data/artists.ts`: BAESAN·HYUN JIZEL에 팬덤(각각 "에아"/"피터", 같은 유닛 파트너와 동일)을 추가해 네 멤버 모두 팬덤 항목을 갖도록 통일, HAM BOM의 `age: "25"` 임시값을 실제 생일(`2002.09.06`)로 교체, SERINA의 임시 인스타그램 계정 제거

## 주요 변경사항

- `README.md` 전면 개편
- `src/data/artists.ts` 멤버 데이터 수정

## 관련 파일

- `README.md`
- `src/data/artists.ts`

## 완료 조건

- [x] 목차가 7장 구조로 정리된다
- [x] 능력 순환 명칭이 문서 전체에서 하나로 통일된다
- [x] 네 멤버 모두 동일한 항목(생일/팬덤)을 가진다
- [x] `tsc --noEmit`이 통과한다 (데이터 타입 변경 검증)

## 실제 완료 여부

**완료.**

---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HYUN JIZEL** | `DONE` | `3` |
','2026-09-12T16:20:33Z','2026-09-12T16:20:58Z','2026-09-12T16:20:58Z','https://github.com/seune-h0203/cones/issues/37'),
(36,5434529187,'seune-h0203','## 작업 목적

GitHub Pages 배포 빌드가 Supabase 접속 정보 없이 실행되어, 실제 배포된 사이트에서는 커머스가 항상 비활성 상태로 나오던 문제를 해결한다.

## 구현 내용

- `.github/workflows/deploy.yml`의 빌드 스텝에 `VITE_SUPABASE_URL`, `VITE_SUPABASE_ANON_KEY` 환경변수 추가
- anon(publishable) key는 클라이언트에 공개되도록 설계된 키이며 실제 데이터 보호는 RLS가 담당하므로, 저장소에 평문으로 있어도 새로운 보안 위험이 없음을 확인하고 채택 (서버 전용 `service_role` 키는 어디에도 사용하지 않음)

## 주요 변경사항

- `.github/workflows/deploy.yml`

## 관련 파일

- `.github/workflows/deploy.yml`

## 완료 조건

- [x] `main` push 후 GitHub Actions 빌드가 성공한다
- [x] 배포된 사이트의 JS 번들에 실제 Supabase 프로젝트 URL이 포함되고 placeholder 값은 제거된다
- [x] `service_role` 키는 어디에도 사용하지 않는다

## 실제 완료 여부

**완료.** GitHub Actions 실행 결과(success)와, 배포된 번들 안에 실제 프로젝트 참조(`ljkfoiiefhszjufxjbep`)가 포함되고 placeholder 문자열은 제거된 것을 직접 확인했다.

---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HAM BOM** | `DONE` | `1` |
','2026-09-12T16:20:31Z','2026-09-12T16:20:56Z','2026-09-12T16:20:56Z','https://github.com/seune-h0203/cones/issues/36'),
(35,5434528980,'seune-h0203','## 작업 목적

GitHub Pages 서브패스(`/cones/`) 배포 환경에서 발견된 두 가지 실사용 버그 — 네비게이션이 도메인 루트로 이탈하는 문제와 상품 상세 페이지 사진이 깨지는 문제 — 를 수정한다.

## 구현 내용

- **Navbar 서브패스 이탈**: `Navbar.tsx`의 섹션 링크가 `href={"/" + item.path}`로 도메인 루트 기준 절대경로를 하드코딩하고 있어, `/cones/` 하위에 배포된 사이트에서 ORIGINS/ARTISTS 등을 누르면 `/cones/`가 빠진 `https://seune-h0203.github.io/#artists`로 이동하던 버그를 수정. `BrowserRouter`의 `basename`과 동일한 런타임 감지값(`window.__CONES_BASE__`)을 사용하도록 변경.
- **상품 이미지 깨짐**: `utils/asset.ts`가 Vite 빌드타임 상대 경로(`import.meta.env.BASE_URL`, 값은 `"./"`)를 그대로 써서, `/shop/product/:slug`처럼 라우트가 3단계 깊어지면 브라우저의 상대경로 해석 규칙상 배포 루트가 아니라 상위 경로 한 단계만 벗겨진 잘못된 URL이 만들어져 이미지가 404 나던 버그를 수정. 동일하게 `window.__CONES_BASE__` 기준 절대경로로 변경.
- **MD 상품 이미지 화질**: 원본 MD 포스터(1536×1024)에서 상품 하나가 차지하는 영역이 약 250~290px로 작아, Shop 4열 고정 그리드(카드당 ~300~390px)와 Product Detail 480px 컬럼이 이를 최대 ~2배로 확대 표시해 흐릿하게 보이던 문제를, 그리드 컬럼을 `auto-fill, minmax(240px, 1fr)`로 상품 원본 해상도에 가깝게, Detail 컬럼을 320px로 줄여 완화.

## 주요 변경사항

- `src/components/Navbar.tsx`
- `src/utils/asset.ts`
- `src/pages/shop/shop.module.css`

## 관련 파일

- `src/components/Navbar.tsx`
- `src/utils/asset.ts`
- `src/pages/shop/shop.module.css`

## 완료 조건

- [x] `https://seune-h0203.github.io/cones/`에서 네비게이션이 `/cones/` 하위에서만 이동한다
- [x] `/shop/product/:slug` 페이지의 상품 사진이 정상 로드된다
- [x] Shop / Detail 이미지 확대 배율이 완화된다

## 실제 완료 여부

**완료.** 실 배포 사이트(`https://seune-h0203.github.io/cones/`)에 각 수정을 순서대로 배포한 뒤, `curl`로 이미지 URL 200 응답과 GitHub Actions 빌드 성공을 직접 확인했다.

---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HAM BOM** | `DONE` | `3` |
','2026-09-12T16:20:28Z','2026-09-14T05:09:04Z','2026-09-12T16:20:54Z','https://github.com/seune-h0203/cones/issues/35'),
(34,5434528582,'seune-h0203','## 작업 목적

주문 상세 / My Orders 화면에서 실제 구매했던 상품 사진을 보여줄 수 있도록, 주문 시점의 상품 이미지를 주문 데이터에 별도로 저장한다.

## 구현 내용

- `order_items` 테이블에 `image` 컬럼 추가 (`ALTER TABLE ... ADD COLUMN IF NOT EXISTS`로 기존 배포 환경에도 안전하게 적용)
- `create_order()` RPC가 주문 생성 시 상품의 `image`를 `order_items`에 함께 복사하도록 갱신 — `product_name`과 같은 이유로, 이후 상품이 삭제·변경돼도 과거 주문 화면은 그대로 유지됨
- `MyOrders.tsx`에서 PostgREST embedded resource(`orders?select=*,order_items(id,product_name,image)`)로 주문별 썸네일 조회, `OrderComplete.tsx`에서 라인 아이템별 이미지 렌더링

## 주요 변경사항

- `supabase/schema.sql` — `order_items.image` 컬럼 및 `create_order()` INSERT 구문 갱신
- `src/lib/database.types.ts` — `OrderItemRow.image` 필드 추가
- `src/pages/shop/OrderComplete.tsx`, `MyOrders.tsx`, `shop.module.css` — 썸네일 렌더링

## 관련 파일

- `supabase/schema.sql`
- `src/lib/database.types.ts`
- `src/pages/shop/OrderComplete.tsx`
- `src/pages/shop/MyOrders.tsx`
- `src/pages/shop/shop.module.css`

## 완료 조건

- [x] 새로 생성되는 주문의 `order_items.image`가 실제로 채워진다
- [x] My Orders 목록과 주문 상세 페이지에 상품 이미지가 표시된다
- [x] 마이그레이션 이전에 생성된 주문은 에러 없이 빈 자리로 표시된다 (하위 호환)

## 실제 완료 여부

**완료.** 실제 Supabase 프로젝트에 `ALTER TABLE`과 갱신된 RPC를 배포한 뒤, 신규 주문(SERINA KEYRING) 생성 → `order_items.image`에 `images/md/products/rina-keyring.jpg`가 정상적으로 채워지는 것과 embedded 쿼리 결과까지 REST API로 직접 확인했다.

---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HAM BOM** | `DONE` | `2` |
','2026-09-12T16:20:25Z','2026-09-12T16:20:51Z','2026-09-12T16:20:51Z','https://github.com/seune-h0203/cones/issues/34'),
(33,5434528380,'seune-h0203','## 작업 목적

랜딩페이지 MD 배너에서 이어지는 실제 커머스 UI(Shop → Product Detail → Cart → Checkout → Order Complete → My Orders)와 회원가입/로그인 화면을 구현한다.

## 구현 내용

- `react-router-dom`의 `BrowserRouter`를 재도입해 One Page Landing(`Home`)과 커머스 라우트를 함께 렌더링
- Shop(아티스트 필터, 32개 상품 그리드), Product Detail, Cart(수량 변경/삭제, 소계), Checkout(주문 생성), Order Complete(주문 요약), My Orders(주문 목록 + mock 결제 버튼) 페이지
- `AuthContext`(Supabase 세션/회원가입/로그인/로그아웃), `CartContext`(장바구니 상태, 낙관적 업데이트, `ensureCartId`) 신규
- Navbar에 CART(수량 배지) / LOGIN / MY ORDERS 링크 추가, 아티스트 프로필 모달의 "OFFICIAL MD" 버튼을 실제 `/shop?artist=` 딥링크로 연결
- 로그인하지 않은 사용자가 `/cart`, `/checkout`, `/mypage/orders` 접근 시 `/login`으로 리다이렉트

## 주요 변경사항

- `src/App.tsx` — BrowserRouter/Routes 추가 (랜딩페이지 히어로/스크롤 구조는 변경 없음)
- `src/pages/shop/*`, `src/pages/auth/*` 신규
- `src/contexts/AuthContext.tsx`, `src/contexts/CartContext.tsx` 신규
- `src/components/Navbar.tsx`, `src/components/ArtistProfileModal.tsx`, `src/pages/Home.tsx` 커머스 딥링크 연동
- `public/404.html` 신규 — GitHub Pages SPA 라우팅 리다이렉트

## 관련 파일

- `src/App.tsx`
- `src/pages/shop/Shop.tsx`, `ProductDetail.tsx`, `Cart.tsx`, `Checkout.tsx`, `OrderComplete.tsx`, `MyOrders.tsx`
- `src/pages/auth/Login.tsx`, `Signup.tsx`
- `src/contexts/AuthContext.tsx`, `src/contexts/CartContext.tsx`
- `src/components/Navbar.tsx`, `src/components/ArtistProfileModal.tsx`, `src/pages/Home.tsx`
- `public/404.html`

## 완료 조건

- [x] Shop → Product Detail → Cart → Checkout → Order Complete → My Orders 전체 흐름이 실제 로그인 세션과 DB로 동작한다
- [x] 랜딩페이지 첫 화면(히어로)은 이 작업 과정에서 수정되지 않았다
- [x] 로그인하지 않은 사용자는 장바구니/주문 페이지에서 로그인 화면으로 리다이렉트된다
- [x] `npm run build`(`tsc --noEmit` + `vite build`)가 통과한다

## 실제 완료 여부

**완료.** 실제 Supabase 프로젝트에 연결해 회원가입 → 로그인 → 상품 조회 → 장바구니 담기 → 결제 → 주문 완료 → My Orders 조회까지, 프론트엔드가 호출하는 것과 동일한 요청을 REST API 레벨로 직접 실행해 검증했다 (이 작업 환경에 브라우저 자동화 도구가 없어 UI 스크린샷 대신 API/빌드 레벨로 검증).

---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HAM BOM** | `DONE` | `5` |
','2026-09-12T16:20:23Z','2026-09-14T05:07:34Z','2026-09-12T16:20:49Z','https://github.com/seune-h0203/cones/issues/33'),
(32,5434527969,'seune-h0203','## 작업 목적

MD Collection 이미지를 하나의 상품으로 뭉뚱그리지 않고, 4명 × 8종 = 32개의 실제 상품을 실제 데이터베이스로 관리하며 주문 생성 시 서버 측에서 가격/재고를 재계산하는 백엔드를 구축한다.

## 구현 내용

- Supabase(Postgres + Auth + PostgREST) 프로젝트 연동
- `products` / `carts` / `cart_items` / `orders` / `order_items` 5개 테이블 + 인덱스 정의
- 전 테이블 Row Level Security 적용 — 사용자는 자신의 장바구니/주문만 읽고 쓸 수 있음
- `create_order()` SECURITY DEFINER RPC: 장바구니 내용을 서버에서 재검증(재고 `FOR UPDATE` 잠금, 가격 재계산, 배송비 계산)한 뒤 orders/order_items 생성, 재고 차감, 품절 처리, 장바구니 비우기
- `mock_pay_order()` RPC: `PENDING → PAID` 목업 결제 전환 (실 PG 연동 전 시연용)
- 32개 상품 시드 데이터 (`ON CONFLICT DO UPDATE`로 재실행 안전)

## 주요 변경사항

- `supabase/schema.sql` 신규 (테이블, RLS, RPC, 시드)
- `src/lib/supabase.ts` 신규 (Supabase 클라이언트, `isCommerceConfigured` 플래그)
- `src/lib/database.types.ts` 신규 (테이블 타입 정의)
- `.env.example`, `.gitignore`(.env 제외) 추가

## 관련 파일

- `supabase/schema.sql`
- `src/lib/supabase.ts`
- `src/lib/database.types.ts`
- `.env.example`

## 완료 조건

- [x] 5개 테이블과 RLS 정책이 실제 Supabase 프로젝트에 배포된다
- [x] `create_order()`가 클라이언트가 보낸 총액이 아니라 서버에서 재계산한 금액으로 주문을 생성한다
- [x] 재고가 0이 되면 자동으로 SOLD_OUT 처리된다
- [x] 다른 사용자의 장바구니/주문을 조회·수정할 수 없다 (RLS)

## 실제 완료 여부

**완료.** REST API로 실제 회원가입 → 장바구니 담기 → `create_order()` 호출 → orders/order_items 생성 → 재고 차감(37→35 등) 확인 → 다른 계정으로 접근 차단까지 전 구간을 직접 호출해 검증했다. 검증 도중 `create_order()`의 `where order_id = v_order_id` 구문이 함수의 OUT 파라미터명과 충돌해 "ambiguous column" 오류가 발생하는 버그를 발견해 `oi.order_id`로 수정, 재배포 후 재검증까지 완료했다.

---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HAM BOM** | `DONE` | `5` |
','2026-09-12T16:20:20Z','2026-09-14T05:11:22Z','2026-09-12T16:20:46Z','https://github.com/seune-h0203/cones/issues/32'),
(13,5408328962,'seune-h0203','## 작업 목적

3분 안에 CONES의 세계관·팀 협업 과정·결과물을 보여줄 수 있도록 발표와 Demo 흐름을 확정한다.


## Task

- [x] 1. CONES 소개
- [x] 2. TWO ORIGINS, ONE SYSTEM
- [x] 3. AI UNIT / COMPUTER UNIT
- [x] 4. 4명의 Artist
- [x] 5. CONNECTION : 00
- [ ] 6. GitHub Kanban
- [ ] 7. Landing Page Demo


## Acceptance Criteria

- [ ] 3분 이내 발표 가능
- [ ] Demo 순서 확정
- [ ] GitHub Repository 링크 준비
- [ ] GitHub Project 링크 준비
- [ ] Landing Page 링크 준비


---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HYUN JIZEL** | `BACKLOG` | `3` |
','2026-09-10T05:47:36Z','2026-09-14T05:06:52Z','','https://github.com/seune-h0203/cones/issues/13'),
(12,5408328868,'seune-h0203','## 작업 목적

GitHub Pages에 실제 배포된 프로덕션 사이트가 정상 동작하는지 최종 확인한다.


## Task

- [ ] GitHub Pages 접속 확인
- [ ] Home 확인
- [ ] World 확인
- [ ] Artists 확인
- [ ] Artist Detail 확인
- [ ] Project 확인
- [ ] About 확인
- [ ] Images 확인
- [ ] Videos 확인
- [ ] Navigation 확인


## Acceptance Criteria

- [ ] Production 사이트가 정상적으로 열린다.
- [ ] 주요 페이지가 정상적으로 작동한다.


## Note

**선행 조건:** 저장소 `Settings → Pages → Source → GitHub Actions` 설정이 필요하다. 저장소가 방금 생성되었으므로 아직 Pages 배포가 한 번도 실행된 적 없다. 대상 URL: https://seune-h0203.github.io/cones/


---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HAM BOM** | `BACKLOG` | `2` |
','2026-09-10T05:47:35Z','2026-09-24T07:16:42Z','2026-09-12T16:21:22Z','https://github.com/seune-h0203/cones/issues/12'),
(11,5408328793,'seune-h0203','## 작업 목적

배포 전에 프로덕션 빌드가 타입 오류 없이 통과하는지 확인한다.


## Task

- [ ] `npm run build` 실행
- [ ] 필요 시 `npm run dev` / `npm run preview` 확인
- [ ] TypeScript Error 확인
- [ ] Build Error 확인
- [ ] Import Error 확인
- [ ] Asset Error 확인


## Acceptance Criteria

- [ ] `npm run build`가 성공한다.
- [ ] 치명적인 오류가 없다.


## Note

`npm run build`는 `tsc --noEmit` 후 Vite 프로덕션 빌드를 수행한다.


---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HAM BOM** | `BACKLOG` | `2` |
','2026-09-10T05:47:34Z','2026-09-24T07:16:30Z','2026-09-12T16:21:37Z','https://github.com/seune-h0203/cones/issues/11'),
(10,5408328689,'seune-h0203','## 작업 목적

키보드 사용자와 스크린리더 사용자가 사이트의 주요 기능을 문제없이 사용할 수 있는지 검수한다.


## Task

- [ ] alt text 확인
- [ ] semantic HTML 확인
- [ ] keyboard navigation 확인
- [ ] focus-visible 확인
- [ ] skip link 확인
- [ ] modal focus trap 확인
- [ ] Escape 동작 확인
- [ ] reduced motion 확인


## Acceptance Criteria

- [ ] 주요 기능을 키보드로 사용할 수 있다.
- [ ] 이미지에 적절한 alt가 있다.
- [ ] Modal이 정상적으로 닫힌다.
- [ ] 접근성 관련 치명적인 문제가 없다.


---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **BAESAN** | `BACKLOG` | `3` |
','2026-09-10T05:47:33Z','2026-09-24T07:16:11Z','2026-09-12T16:22:08Z','https://github.com/seune-h0203/cones/issues/10'),
(9,5408328606,'seune-h0203','## 작업 목적

스크롤 기반 연출과 인터랙션이 모든 환경에서 오류 없이 동작하고, 모션 최소화 설정을 존중하는지 확인한다.


## Task

- [x] Scroll Reveal 확인
- [x] ConnectionSequence 확인
- [x] SystemCycle 확인
- [x] AbilityMotif 확인
- [x] Page Transition 확인
- [x] Custom Cursor 확인
- [x] Video Modal 확인


## Acceptance Criteria

- [x] Animation 오류가 없다.
- [x] Scroll Interaction이 정상이다.
- [x] Mobile에서 문제가 발생하지 않는다.
- [x] Reduced Motion 대응이 유지된다.


## Note

`prefers-reduced-motion: reduce` 환경에서 `ConnectionSequence`가 스크롤 애니메이션 대신 완성된 구도로 표시되는지 함께 확인한다.


---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **SERINA** | `BACKLOG` | `3` |
','2026-09-10T05:47:32Z','2026-09-24T07:16:51Z','','https://github.com/seune-h0203/cones/issues/9'),
(7,5408328450,'seune-h0203','## 작업 목적

데스크톱 해상도 전반에서 레이아웃이 깨지지 않고 타이포그래피가 의도대로 보이는지 검수한다.


## Task

- [ ] Navigation 확인
- [ ] Hero 확인
- [ ] Typography 확인
- [ ] Artist Grid 확인
- [ ] World 확인
- [ ] Connection 확인
- [ ] System Cycle 확인
- [ ] Video 확인
- [ ] CTA 확인
- [ ] Footer 확인


## Acceptance Criteria

- [ ] Layout이 깨지지 않는다.
- [ ] 텍스트가 잘리지 않는다.
- [ ] 가로 스크롤이 발생하지 않는다.


---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **SERINA** | `READY` | `3` |
','2026-09-10T05:47:31Z','2026-09-10T07:43:27Z','2026-09-10T06:17:13Z','https://github.com/seune-h0203/cones/issues/7'),
(6,5408328371,'seune-h0203','## 작업 목적

HashRouter 기반 라우팅이 GitHub Pages 정적 호스팅에서 새로고침·딥링크 포함 정상 동작하는지 확인한다.


## Task

- [ ] `/` 확인
- [ ] `#/world` 확인
- [ ] `#/artists` 확인
- [ ] `#/artists/:artistId` 확인 (rina · baesan · hyun-jizel · ham-bom)
- [ ] `#/project` 확인
- [ ] `#/about` 확인
- [ ] Not Found Route 확인


## Acceptance Criteria

- [ ] 모든 Route가 정상 작동한다.
- [ ] HashRouter 구조가 정상이다.
- [ ] GitHub Pages 환경에서 정상적으로 접근된다.


---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HAM BOM** | `BACKLOG` | `3` |
','2026-09-10T05:47:30Z','2026-09-14T05:08:28Z','2026-09-12T16:22:27Z','https://github.com/seune-h0203/cones/issues/6'),
(5,5408328305,'seune-h0203','## 작업 목적

`manifest.json`이 실제로 존재하는 영상 파일만 참조하도록 하고, 없는 경우 SIGNAL PENDING 정책이 유지되는지 확인한다.


## Task

- [ ] Desktop video 확인
- [ ] Mobile video 확인
- [ ] Poster 확인
- [ ] Video path 확인
- [ ] 실제 파일 존재 여부 확인


## Acceptance Criteria

- [ ] 존재하지 않는 파일을 참조하지 않는다.
- [ ] 실제 영상이 정상적으로 연결된다.
- [ ] 영상이 없는 경우 기존 SIGNAL PENDING 정책을 유지한다.


## Note

**현재 상태 확인 결과:** `public/videos/manifest.json`의 `teasers`에는 `baesan`만 등록되어 있다. 홈페이지 `WATCH TEASER` 버튼이 참조하는 `project` 키는 아직 등록되어 있지 않아 포스터 폴백으로 동작한다. 의도된 상태인지 확인 필요.


---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HAM BOM** | `BACKLOG` | `3` |
','2026-09-10T05:47:29Z','2026-09-14T05:06:54Z','2026-09-12T16:22:43Z','https://github.com/seune-h0203/cones/issues/5'),
(4,5408328232,'seune-h0203','## 작업 목적

로컬 dev 환경과 GitHub Pages 서브패스 환경 양쪽에서 모든 이미지 에셋이 정상 로딩되는지 확인한다.


## Task

- [ ] Logo 경로 확인
- [ ] Artist Image 경로 확인
- [ ] Director Image 경로 확인
- [ ] Poster 경로 확인
- [ ] 기타 Image Asset 경로 확인


## Acceptance Criteria

- [ ] Broken Image가 없다.
- [ ] GitHub Pages에서도 Asset이 정상적으로 로딩된다.


## Note

에셋 경로는 `src/utils/asset.ts`의 `asset()`을 통해 `BASE_URL` 기준으로 해석된다. `vite.config.ts`의 `base: "./"` 설정과 함께 확인할 것.


---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HAM BOM** | `READY` | `2` |
','2026-09-10T05:47:29Z','2026-09-24T07:17:05Z','2026-09-12T16:23:02Z','https://github.com/seune-h0203/cones/issues/4'),
(3,5408328139,'seune-h0203','## 작업 목적

모든 라우트가 정상 연결되고 페이지 간 콘텐츠(월드관/유닛/아티스트)가 서로 모순되지 않는지 확인한다.


## Task

- [ ] Home 연결 확인
- [ ] World 연결 확인
- [ ] Artists 연결 확인
- [ ] Artist Detail 연결 확인
- [ ] Project 연결 확인
- [ ] About 연결 확인
- [ ] Not Found 연결 확인


## Acceptance Criteria

- [ ] 모든 페이지가 정상적으로 연결된다.
- [ ] Navigation이 정상 작동한다.
- [ ] 콘텐츠 간 불일치가 없다.


---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HYUN JIZEL** | `IN PROGRESS` | `3` |
','2026-09-10T05:47:28Z','2026-09-14T05:08:03Z','2026-09-12T16:23:17Z','https://github.com/seune-h0203/cones/issues/3'),
(2,5408328022,'seune-h0203','## 작업 목적

4명 아티스트의 프로필 데이터가 로스터·상세 페이지·OG 태그 전반에서 일치하는지 검수한다.


## Task

- [ ] SERINA / BAESAN / HYUN JIZEL / HAM BOM 4명 정보 검수
- [ ] Stage Name 확인
- [ ] Unit 확인
- [ ] Ability 확인
- [ ] Position 확인
- [ ] Image 확인
- [ ] Artist Detail Route 확인


## Acceptance Criteria

- [ ] 4명의 정보가 일치한다.
- [ ] 잘못된 이미지가 없다.
- [ ] Artist Detail 페이지와 정보가 일치한다.


## Note

모든 아티스트 데이터는 `src/data/artists.ts` 단일 소스에서 관리된다. `id`(예: `rina`)는 기존 라우트/에셋 호환을 위해 유지하되, 노출 텍스트는 **SERINA / 세리나**로 표기되는지 확인한다.


---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **SERINA** | `READY` | `2` |
','2026-09-10T05:47:27Z','2026-09-14T05:07:41Z','2026-09-10T07:19:50Z','https://github.com/seune-h0203/cones/issues/2'),
(1,5408327922,'seune-h0203','## 작업 목적

CONES 최종 제출까지의 모든 작업을 Kanban으로 관리하고, 팀원별 작업 배분과 진행 상태를 실제 상황과 일치시킨다.


## Task

- [ ] 전체 작업 현황 확인
- [ ] Kanban 상태 관리
- [ ] Milestone 관리
- [ ] 팀원 작업 배분
- [ ] 최종 제출 상태 확인


## Acceptance Criteria

- [ ] 모든 주요 작업이 Kanban에 등록되어 있다.
- [ ] 담당자가 명확하다.
- [ ] 작업 상태가 실제 진행 상황과 일치한다.
- [ ] 최종 제출 전 모든 작업의 상태를 확인할 수 있다.


---

| 담당 | Kanban Status | Story Point |
|---|---|---|
| **HYUN JIZEL** | `IN PROGRESS` | `3` |
','2026-09-10T05:47:26Z','2026-09-14T05:07:15Z','2026-09-10T06:17:02Z','https://github.com/seune-h0203/cones/issues/1')) v(issue_number,github_issue_id,author_login,body,created_at,updated_at,closed_at,source_url) on t.github_issue_number=v.issue_number on conflict (task_id) do update set github_issue_id=excluded.github_issue_id,author_login=excluded.author_login,body=excluded.body,created_at=excluded.created_at,updated_at=excluded.updated_at,closed_at=excluded.closed_at,source_url=excluded.source_url;
insert into public.issue_comments(comment_id,task_id,author_login,created_at,updated_at,body,source_url) select v.comment_id,t.task_id,v.author_login,v.created_at::timestamptz,v.updated_at::timestamptz,v.body,v.source_url from public.tasks t join (values
(5647147661,9,'seune-h0203','2026-09-12T16:23:34Z','2026-09-12T16:23:34Z','**정리 작업 중 검토 — OPEN 유지**

이 환경에는 브라우저 자동화 도구(chromium-cli 등)가 없어, 스크롤 인터랙션·애니메이션이 실제 화면에서 오류 없이 동작하는지 라이브로 확인할 수 없었습니다. 코드상 `ConnectionSequence`/`SystemCycle`/`AbilityMotif`/`PageTransition`/`CustomCursor`/`VideoModal`과 `prefers-reduced-motion` 분기가 존재하는 것은 확인했지만, 이것만으로 "Animation 오류 없음"을 단정할 수 없어 임의로 DONE 처리하지 않고 OPEN으로 남겨둡니다. 실제 브라우저에서의 시각 검증이 필요합니다.','https://github.com/seune-h0203/cones/issues/9#issuecomment-5647147661'),
(5647147446,13,'seune-h0203','2026-09-12T16:23:32Z','2026-09-12T16:23:32Z','**정리 작업 중 검토 — OPEN 유지**

이번 칸반 정리 세션에서 열려 있던 이슈들을 코드/배포 상태 기준으로 검증했습니다. 이 이슈는 실제 발표·데모 리허설이 필요한 사람 손의 작업이라 코드 상태로 완료 여부를 판단할 수 없어 임의로 닫지 않고 OPEN으로 남겨둡니다.','https://github.com/seune-h0203/cones/issues/13#issuecomment-5647147446'),
(5647145056,3,'seune-h0203','2026-09-12T16:23:16Z','2026-09-12T16:23:16Z','**검토 결과 — 구조 변경으로 대체(superseded), DONE 아님 · not planned로 종료**

이 이슈의 체크리스트(Home/World/Artists/Artist Detail/Project/About/Not Found가 서로 다른 라우트로 연결되는지 확인)는 다중 페이지 구조를 전제로 합니다. 이후 사이트는 One Page Landing Page로 통합되어 World/Artists/Artist Detail/Project/About/Not Found는 더 이상 라우팅되지 않는 레거시 파일로만 남아 있습니다(README 4.2, 5.3 참고). 즉 "World 연결 확인"처럼 존재하지 않는 라우트를 체크할 방법이 없어, 이 체크리스트를 문자 그대로 완료 처리할 수는 없습니다.

현재 아키텍처에서 이에 대응하는 라우팅·콘텐츠 연결 검증은 #6, #4, #35에서 실제로 수행했습니다. 억지로 DONE 처리하지 않고 "구조 변경으로 대체됨"으로 닫습니다.','https://github.com/seune-h0203/cones/issues/3#issuecomment-5647145056'),
(5647142722,4,'seune-h0203','2026-09-12T16:23:00Z','2026-09-12T16:23:00Z','**검증 결과 — DONE 처리 (이번 세션에서 실제 버그 발견·수정)**

이 이슈가 우려한 정확히 그 지점(`asset()`의 `BASE_URL` 해석)에서 실제 버그를 발견해 수정했습니다: `import.meta.env.BASE_URL`(빌드타임 상대값 `"./"`)을 그대로 쓰면 라우트가 한 단계보다 깊어질 때(`/shop/product/:slug`) 브라우저의 상대경로 해석 규칙상 깨진 URL이 만들어져 상품 이미지가 404가 났습니다. `window.__CONES_BASE__`(런타임에 감지한 실제 배포 루트) 기준으로 바꿔 수정했고, 배포된 사이트에서 `curl`로 이미지 200 응답을 직접 확인했습니다.

- Logo / Artist Image / Director Image / Poster 등 기존 경로: 원래도 정상 (단일 세그먼트 라우트라 우연히 문제 없었음)
- MD 상품 이미지 등 새 경로: 버그 있었음 → 수정 완료 및 검증

세부 내용은 #35(FIX)에 기록했습니다.','https://github.com/seune-h0203/cones/issues/4#issuecomment-5647142722'),
(5647140018,5,'seune-h0203','2026-09-12T16:22:42Z','2026-09-12T16:22:42Z','**검증 결과 — DONE 처리**

`public/videos/manifest.json`과 실제 파일을 직접 대조했습니다:

- `teasers`에 등록된 유일한 항목은 `baesan.desktop: "baesan-teaser.mp4"`
- `public/videos/baesan-teaser.mp4` 파일이 실제로 존재함 (존재하지 않는 파일 참조 없음)
- 등록되지 않은 나머지 멤버(SERINA/HYUN JIZEL/HAM BOM)와 홈 "WATCH TEASER"가 쓰는 `project` 키는 README 4.3에 명시된 대로 포스터 폴백 + `SIGNAL PENDING` 정책이 의도된 현재 상태로 유지되고 있음을 확인

Acceptance Criteria 3항목 모두 충족합니다.','https://github.com/seune-h0203/cones/issues/5#issuecomment-5647140018'),
(5647137869,6,'seune-h0203','2026-09-12T16:22:26Z','2026-09-12T16:22:26Z','**검증 결과 — DONE 처리 (체크리스트는 구 아키텍처 기준, 현재 구조로 대체 검증)**

이 이슈의 체크리스트(`HashRouter`, `#/world`, `#/artists/:id` 등)는 라우터를 `BrowserRouter`로, 라우트를 `/`, `/shop`, `/shop/product/:slug` 등으로 완전히 교체한 커머스 MVP 이전 구조 기준입니다. 옛 라우트는 더 이상 존재하지 않아 문자 그대로는 검증할 수 없지만, 이번 세션에서 현재 구조 기준의 동일한 관심사 — "GitHub Pages 정적 호스팅에서 새로고침·딥링크 포함 정상 동작하는가" — 를 실제로 검증하고 버그도 하나 고쳤습니다:

- `public/404.html` + `window.__CONES_BASE__` 런타임 감지로 `/shop`, `/shop/product/:slug` 등 딥링크·새로고침이 정상 동작하는 것을 `curl`로 확인
- Navbar 섹션 링크가 서브패스를 무시하고 도메인 루트로 이탈하던 버그 발견·수정·재배포 검증 (#35)

세부 내용은 #35(FIX)에 기록했습니다.','https://github.com/seune-h0203/cones/issues/6#issuecomment-5647137869'),
(5647135277,10,'seune-h0203','2026-09-12T16:22:07Z','2026-09-12T16:22:07Z','**검증 결과 — DONE 처리 (코드 레벨 검증)**

이 환경에는 실제 스크린리더/브라우저 자동화 도구가 없어 라이브 인터랙션 테스트 대신 코드 검토로 각 항목의 구현 여부를 확인했습니다:

- `alt` text — 아티스트/디렉터/상품 이미지 전반에 의미 있는 `alt` 부여 확인
- semantic HTML — `<button>`/`<a>` 실제 사용, `<header>`/`<main>`/`<nav>` 랜드마크 확인
- keyboard navigation / focus-visible — 전역 포커스 스타일 확인
- skip link — `App.tsx`의 `<a href="#main" className="u-skip">` 확인
- modal focus trap / Escape — `useFocusTrap.ts`(`useFocusTrap`/`useScrollLock`) 및 `ArtistProfileModal`/`VideoModal`의 Escape 핸들러 확인
- reduced motion — `useMedia.ts`의 `useReducedMotion`과 `prefers-reduced-motion` CSS 분기 다수 확인 (`global.css` 등)

라이브 스크린리더 테스트까지는 아니지만, Acceptance Criteria가 요구하는 메커니즘이 코드에 실제로 존재함을 확인했습니다.','https://github.com/seune-h0203/cones/issues/10#issuecomment-5647135277'),
(5647131317,11,'seune-h0203','2026-09-12T16:21:36Z','2026-09-12T16:21:36Z','**검증 결과 — DONE 처리**

`npm run build`와 동일한 `tsc --noEmit` → `vite build` 절차를 이번 세션에서 여러 차례(커머스 MVP 추가, 버그 수정, README/데이터 변경 등 매 변경 후) 반복 실행했고, TypeScript 오류·빌드 오류·import 오류·asset 오류 없이 전부 성공했습니다. 최종 빌드 로그:

```
✓ 141 modules transformed.
✓ built in 3-5s (매 실행)
```

`react-router-dom`, `@supabase/supabase-js` 등 신규 의존성 추가 이후에도 동일하게 통과합니다.','https://github.com/seune-h0203/cones/issues/11#issuecomment-5647131317'),
(5647129629,12,'seune-h0203','2026-09-12T16:21:21Z','2026-09-12T16:21:21Z','**검증 결과 — DONE 처리**

체크리스트가 작성된 시점(Home/World/Artists/Artist Detail/About이 별도 라우트였던 구조) 이후, 사이트는 One Page Landing Page로 통합되어 해당 페이지들은 모두 `/`의 섹션으로 흡수되었습니다(README 4.2 참고). 그래서 개별 항목을 문자 그대로 체크할 수는 없지만, 핵심 Acceptance Criteria인 "Production 사이트가 정상적으로 열린다 / 주요 페이지가 정상적으로 작동한다"는 이번 세션에서 실제로 검증했습니다:

- `https://seune-h0203.github.io/cones/` 및 하위 라우트(`/shop`, `/shop/product/:slug`, `/cart` 등) `curl` 200 확인
- 최신 GitHub Actions 배포(run 성공) 확인
- 이미지·네비게이션 관련 실사용 버그 2건을 이번 세션에 직접 발견·수정·재배포까지 완료 (#35 참고)

새 아키텍처 기준의 배포 확인 세부 내역은 #35(FIX), #36(DEVOPS)에 기록했습니다.','https://github.com/seune-h0203/cones/issues/12#issuecomment-5647129629'),
(5647125563,32,'seune-h0203','2026-09-12T16:20:45Z','2026-09-12T16:20:45Z','이번 세션에서 실제 구현·배포·검증까지 완료되어 DONE 처리합니다.','https://github.com/seune-h0203/cones/issues/32#issuecomment-5647125563'),
(5647125834,33,'seune-h0203','2026-09-12T16:20:48Z','2026-09-12T16:20:48Z','이번 세션에서 실제 구현·배포·검증까지 완료되어 DONE 처리합니다.','https://github.com/seune-h0203/cones/issues/33#issuecomment-5647125834'),
(5647126157,34,'seune-h0203','2026-09-12T16:20:50Z','2026-09-12T16:20:50Z','이번 세션에서 실제 구현·배포·검증까지 완료되어 DONE 처리합니다.','https://github.com/seune-h0203/cones/issues/34#issuecomment-5647126157'),
(5647126427,35,'seune-h0203','2026-09-12T16:20:53Z','2026-09-12T16:20:53Z','이번 세션에서 실제 구현·배포·검증까지 완료되어 DONE 처리합니다.','https://github.com/seune-h0203/cones/issues/35#issuecomment-5647126427'),
(5647126667,36,'seune-h0203','2026-09-12T16:20:55Z','2026-09-12T16:20:55Z','이번 세션에서 실제 구현·배포·검증까지 완료되어 DONE 처리합니다.','https://github.com/seune-h0203/cones/issues/36#issuecomment-5647126667'),
(5647126860,37,'seune-h0203','2026-09-12T16:20:57Z','2026-09-12T16:20:57Z','이번 세션에서 실제 구현·배포·검증까지 완료되어 DONE 처리합니다.','https://github.com/seune-h0203/cones/issues/37#issuecomment-5647126860')) v(comment_id,issue_number,author_login,created_at,updated_at,body,source_url) on t.github_issue_number=v.issue_number on conflict (comment_id) do update set author_login=excluded.author_login,created_at=excluded.created_at,updated_at=excluded.updated_at,body=excluded.body,source_url=excluded.source_url;
alter table public.issue_details enable row level security;
drop policy if exists "issue_details_read_anon" on public.issue_details;
drop policy if exists "issue_details_read_authenticated" on public.issue_details;
create policy "issue_details_read_anon" on public.issue_details for select to anon using (true);
create policy "issue_details_read_authenticated" on public.issue_details for select to authenticated using (true);
alter table public.issue_comments enable row level security;
drop policy if exists "issue_comments_read_anon" on public.issue_comments;
drop policy if exists "issue_comments_read_authenticated" on public.issue_comments;
create policy "issue_comments_read_anon" on public.issue_comments for select to anon using (true);
create policy "issue_comments_read_authenticated" on public.issue_comments for select to authenticated using (true);
alter table public.issue_timeline_events enable row level security;
drop policy if exists "issue_timeline_events_read_anon" on public.issue_timeline_events;
drop policy if exists "issue_timeline_events_read_authenticated" on public.issue_timeline_events;
create policy "issue_timeline_events_read_anon" on public.issue_timeline_events for select to anon using (true);
create policy "issue_timeline_events_read_authenticated" on public.issue_timeline_events for select to authenticated using (true);
alter table public.project_status_history enable row level security;
drop policy if exists "project_status_history_read_anon" on public.project_status_history;
drop policy if exists "project_status_history_read_authenticated" on public.project_status_history;
create policy "project_status_history_read_anon" on public.project_status_history for select to anon using (true);
create policy "project_status_history_read_authenticated" on public.project_status_history for select to authenticated using (true);
alter table public.projects enable row level security;
drop policy if exists "projects_read_anon" on public.projects;
drop policy if exists "projects_read_authenticated" on public.projects;
create policy "projects_read_anon" on public.projects for select to anon using (true);
create policy "projects_read_authenticated" on public.projects for select to authenticated using (true);
alter table public.users enable row level security;
drop policy if exists "users_read_anon" on public.users;
drop policy if exists "users_read_authenticated" on public.users;
create policy "users_read_anon" on public.users for select to anon using (true);
create policy "users_read_authenticated" on public.users for select to authenticated using (true);
alter table public.statuses enable row level security;
drop policy if exists "statuses_read_anon" on public.statuses;
drop policy if exists "statuses_read_authenticated" on public.statuses;
create policy "statuses_read_anon" on public.statuses for select to anon using (true);
create policy "statuses_read_authenticated" on public.statuses for select to authenticated using (true);
alter table public.milestones enable row level security;
drop policy if exists "milestones_read_anon" on public.milestones;
drop policy if exists "milestones_read_authenticated" on public.milestones;
create policy "milestones_read_anon" on public.milestones for select to anon using (true);
create policy "milestones_read_authenticated" on public.milestones for select to authenticated using (true);
alter table public.tasks enable row level security;
drop policy if exists "tasks_read_anon" on public.tasks;
drop policy if exists "tasks_read_authenticated" on public.tasks;
create policy "tasks_read_anon" on public.tasks for select to anon using (true);
create policy "tasks_read_authenticated" on public.tasks for select to authenticated using (true);
alter table public.task_assignees enable row level security;
drop policy if exists "task_assignees_read_anon" on public.task_assignees;
drop policy if exists "task_assignees_read_authenticated" on public.task_assignees;
create policy "task_assignees_read_anon" on public.task_assignees for select to anon using (true);
create policy "task_assignees_read_authenticated" on public.task_assignees for select to authenticated using (true);
commit;
